version: 1.0.{build}
#skip_non_tags: true
before_build:
- cmd: choco install redis-64
- cmd: redis-server --service-install
- cmd: redis-server --service-start
- cmd: nuget restore src\NServiceBus.Redis.sln
build:
  project: src\NServiceBus.Redis.sln
  verbosity: normal
deploy:
  provider: NuGet
  api_key:
    secure: TKnwhPTFwVbOiHtIAZTDECTJAeWUtB1vJc6Exs/rvZGJaLYaQNXMqGrPJFe0VC5g
  skip_symbols: false
  artifact: /.*\.nupkg/