version: 1.0.{build}
skip_non_tags: true
before_build:
- cmd: nuget restore src\NServiceBus.Redis.sln
build:
  project: src\NServiceBus.Redis.sln
  verbosity: detailed
deploy:
  provider: NuGet
  api_key:
    secure: TKnwhPTFwVbOiHtIAZTDECTJAeWUtB1vJc6Exs/rvZGJaLYaQNXMqGrPJFe0VC5g
  skip_symbols: false
  artifact: /.*\.nupkg/